version: "3"
services:
  api:
    build: .
    container_name: menu
    external_links: 
      - db-postgres:db-postgres
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - database
    environment:
      - PYTHONUNBUFFERED=1
  database:
    image: "postgres"
    restart: always
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d 
      - postgres:/var/lib/postgresql/data/
volumes:
  postgres:
